# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nword.proto\x12\x07mscword\"9\n\x0e\x43onvertRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\"0\n\x0c\x43onvertReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2M\n\x0bWordService\x12>\n\x0c\x43onvertToPDF\x12\x17.mscword.ConvertRequest\x1a\x15.mscword.ConvertReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'word_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERTREQUEST']._serialized_start=23
  _globals['_CONVERTREQUEST']._serialized_end=80
  _globals['_CONVERTREPLY']._serialized_start=82
  _globals['_CONVERTREPLY']._serialized_end=130
  _globals['_WORDSERVICE']._serialized_start=132
  _globals['_WORDSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope) 